language: php
php:
  - 5.4.12

mysql:
  database: drupal
  username: root
  encoding: utf8

before_script:
 - mysql -e 'create database drupal;'
 - pyrus channel-discover pear.drush.org
 - pyrus install drush/drush-devel
 - phpenv rehash
 # --no-cache is must-have due to http://drupal.org/node/1630220
 - drush dl drupal-8 --no-cache
 - cd drupal-*
 - drush si standard --db-url=mysql://root:@localhost/drupal --yes
 - drush en simpletest --yes
 - drush dl moopapi --dev --no-cache
 - drush en moopapi --yes
 - wget http://drupalcode.org/project/drupal.git/blob_plain/refs/heads/7.x:/modules/simpletest/simpletest.test
 - drush cc all
 - drush runserver --server=builtin 8080 &
 - sleep 4
 - drush vset simpletest_verbose FALSE --yes
 - ls -la

script: php ./core/scripts/run-tests.sh --php ~/.phpenv/versions/5.4.12/bin/php --url 'http://127.0.0.1:8080' --xml simpletest.xml --file simpletest.test
#drush test-run --xml --file=simpletest.test --uri=http://127.0.0.1:8080
