language: php
php:
  - 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8

before_script:
 - mysql -e 'create database drupal;'
 - pyrus channel-discover pear.drush.org
 - pyrus install drush/drush-devel
 - phpenv rehash
 - cd ..
 - ls -la
 # --no-cache is must-have due to http://drupal.org/node/1630220
 - drush dl drupal-7 --dev --no-cache
 - cd drupal-*
 # This patch is necessary for Simpletest-tests success.
 #- cp ../drupal7-moopapi/add_moopapi_to_install_profiles.patch add_moopapi_to_install_profiles.patch
 # @todo Patching doesn't work - so replace files with patched.
 #- git apply -p0 --directory=. --verbose add_moopapi_to_install_profiles.patch
 #- git apply -p1 --directory=. --verbose add_moopapi_to_install_profiles.patch
 #- patch -p0 -d . < add_moopapi_to_install_profiles.patch --verbose
 #- patch -p1 -d . < add_moopapi_to_install_profiles.patch --verbose
 # DEBUG
 #- vi profiles/standard/standard.info.rej
 - rm profiles/standard/standard.info
 - cp ../drupal7-moopapi/patch/standard.info profiles/standard/standard.info
 - rm profiles/minimal/minimal.info
 - cp ../drupal7-moopapi/patch/minimal.info profiles/minimal/minimal.info
 - cp -R ../drupal7-moopapi sites/all/modules/moopapi
 - drush si standard --db-url=mysql://root:@localhost/drupal --yes
 #- drush make sites/all/modules/moopapi/moopapi.make .
 # DEBUG: was patch applied?
 #- vi profiles/standard/standard.info
 # Replace tests with D6 tests.
 - rm modules/simpletest/simpletest.test
 - wget --output-document=modules/simpletest/simpletest.test http://drupalcode.org/project/simpletest.git/blob_plain/refs/heads/6.x-2.x:/simpletest.test
 - drush en simpletest --yes
 #- cd sites/all/modules/moopapi
 #- mkdir core
 #- cd core
 - drush en moopapi --yes
 # ?Do we need it?
 #- drush php-eval "module_load_include('test', 'moopapi', 'core/simpletest');";
 # To make test file discoverable.
 #- ls -la
 # Up to Drupal root level.
 #- cd ../../../../../
 # DEBUG
 #- ls -la
 - drush cc all
 - drush runserver --server=builtin 8080 &
 - sleep 4
 #- drush vset simpletest_verbose FALSE --yes
 - drush vset simpletest_verbose TRUE --yes

script: php scripts/run-tests.sh --php ~/.phpenv/versions/5.4.13/bin/php --url 'http://127.0.0.1:8080' --verbose --file modules/simpletest/simpletest.test
#drush test-run --xml --file=sites/all/modules/moopapi/core/simpletest.test --uri=http://127.0.0.1:8080

after_script:
 - ls sites/default/files -la
