language: php
php:
  - 5.4.12

mysql:
  database: drupal
  username: root
  encoding: utf8

before_script:
 - mysql -e 'create database drupal;'
 - pyrus channel-discover pear.drush.org
 - pyrus install drush/drush-devel
 - phpenv rehash
 - cd ..
 - ls -la
 # --no-cache is must-have due to http://drupal.org/node/1630220
 - drush dl drupal-7 --no-cache
 - cd drupal-*
 - cp -R ../drupal7-moopapi sites/all/modules/moopapi
 - drush si standard --db-url=mysql://root:@localhost/drupal --yes
 - drush en simpletest --yes
 - drush en moopapi --yes
 - cd sites/all/modules/moopapi
 - mkdir core
 - wget --output-document=core/simpletest.test http://drupalcode.org/project/simpletest.git/blob_plain/refs/heads/6.x-2.x:/simpletest.test
 - drush php-eval "module_load_include('test', 'moopapi', 'core/simpletest');";
 # To make test file discoverable.
 - cd core
 - ls -la
 # Up to Drupal root level.
 - cd ../../../../../
 # DEBUG
 - ls -la
 - drush cc all
 - drush runserver --server=builtin 8080 &
 - sleep 4
 - drush vset simpletest_verbose FALSE --yes

script: php scripts/run-tests.sh --php ~/.phpenv/versions/5.4.12/bin/php --url 'http://127.0.0.1:8080' --xml simpletest.xml --file sites/all/modules/moopapi/core/simpletest.test
#drush test-run --xml --file=sites/all/modules/moopapi/core/simpletest.test --uri=http://127.0.0.1:8080
