language: php
php:
  - 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8

before_script:
 - mysql -e 'create database drupal;'
 - pyrus channel-discover pear.drush.org
 - pyrus install drush/drush
 - phpenv rehash
 - drush dl drupal-8.x --yes
 - cd drupal-*
 - drush si standard --db-url=mysql://root:@localhost/drupal --yes
 - drush en simpletest --yes
 #- drush dl moopapi --dev
 #- drush en moopapi --yes
 - wget http://drupalcode.org/project/drupal.git/blob_plain/refs/heads/7.x:/modules/simpletest/simpletest.test
 - drush cc all
 - drush runserver --server=builtin 8080 &
 - sleep 4
 - drush vset simpletest_verbose FALSE --yes

script: drush test-run --xml --file=simpletest.test --uri=http://127.0.0.1:8080
